name: Build

on:
  push:
  pull_request:


jobs:
  run:
    strategy:
      fail-fast: false
      matrix:
        build_type: [ Release, Debug ]
        library_type: [ shared, static ]
        os: [ ubuntu-24.04, windows-2025, macos-15 ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Get CMake
        uses: lukka/get-cmake@latest

      - name: Setup MSVC
        if: ${{ contains(matrix.os, 'windows') }}
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install dependencies
        if: ${{ contains(matrix.os, 'ubuntu') }}
        run: sudo apt update && sudo apt install libsystemd-dev

      - name: Build
        uses: lukka/run-cmake@v3
        with:
          cmakeListsOrSettingsJson: 'CMakeListsTxtAdvanced' # Required to respect cmakeAppendedArgs
          cmakeBuildType: ${{ matrix.build_type }}
          buildDirectory: 'build'
          cmakeAppendedArgs: >
            -G Ninja
            -DOSEVENTS_BUILD_SHARED=${{ matrix.library_type == 'shared' }}
            -DOSEVENTS_EXPORT=${{ matrix.library_type == 'shared' }}
